"""empty message

Revision ID: 898916946ac7
Revises: 55b3f3295526
Create Date: 2020-07-13 20:16:51.945318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '898916946ac7'
down_revision = '55b3f3295526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'password_hash')
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.add_column('roles', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
